--- 
pool: default 

trigger: 
  - master 
stages: 
  - stage: build 
    jobs: 
      - job: gameoflifebuild 
        steps: 
          - task: Maven@3 
            inputs: 
              mavenPomFile: pom.xml 
              goals: package 
              publishJUnitResults: true 
              testResultsFiles: '**/surefire-reports/TEST-*.xml' 
              jdkVersionOption: '1.8'  
              javaHomeOption: path 
              jdkDirectory: '/usr/lib/jvm/java-8-openjdk-amd64/'


                 